### PR TITLE
[Lint] Run lint by pre-commit

### LINKED ISSUE #3237: [BUG]: Post-commit workflow does not work!
### 🐛 Describe the bug

Followed from this PR https://github.com/hpcaitech/ColossalAI/pull/3020.

https://github.com/hpcaitech/ColossalAI/blob/280fcdc4856e061688e3aba49c3b53427967fd7b/.github/workflows/post_commit.yml#L84-L85

The 'outputs' condition can be used only if the step or job has 'outputs'.
So the current workflow doesn't work and linting hasn't been done in a while.
It should be changed to use 'outcome'.

References
https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context

I'll create two PRs;
- [ ] Fix post-commit workflow
- [ ] Run pre-commit for all lines that should be changed by lint

### Environment

_No response_

### PR DESCRIPTION
**Pull request by nijkah**
## 📌 Checklist before creating the PR

- [x] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number
fixes #3237 

## 📝 What does this PR do?
Run lint by pre-commit.

https://github.com/hpcaitech/ColossalAI/blob/280fcdc4856e061688e3aba49c3b53427967fd7b/.github/workflows/post_commit.yml#L66-L67
Since the current workflow only checks changed files, it does not edit old lines.

## 💥 Checklist before requesting a review

- [x] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [x] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
Hi  @nijkah , this PR has conflict with the main branch, can you try to resolve the conflict first?

**Comment by nijkah** [comment]
> [View ](/hpcaitech/ColossalAI/pull/3239/files#conversations-menu)
> No unresolved conversations

@FrankLeeeee I fixed some conflicts between yapf and isort!

**Comment by nijkah** [comment]
@FrankLeeeee Hi. The errors on the checks don't seem to be due to this PR. This PR is just formatting.
Should I fix it?

**Comment by FrankLeeeee** [comment]
> @FrankLeeeee Hi. The errors on the checks don't seem to be due to this PR. This PR is just formatting. Should I fix it?

Hi @nijkah , I suspect that the code formatting broke something. Sometimes, the import order can matter, e.g. in C++ and CUDA files. I would like to suggest to format in a module-by-module way. This can bring two benefits.

1. We can approach this matter with a finer granularity, easier to spot what led to the CI failure
2. The amount of code change in a single PR can be reduced, which could make it easier for people who are contributing, e.g. they won't face too many conflicts when pulling a single commit

**Comment by FrankLeeeee** [comment]
If you like, I can handle this together with you. @nijkah

**Comment by nijkah** [comment]
@FrankLeeeee I agree with you. I'll create new PRs based on modules.
Thank you for your suggestion!

**Pull request closed without merging**
