### PR TITLE
[BUG] Add n_fused as an input from native_module

### PR DESCRIPTION
**Pull request by insujang**
## 📌 Checklist before creating the PR

- [ ] I have created an issue for this PR for traceability
- [ ] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs
- [ ] I have installed pre-commit: `pip install pre-commit && pre-commit install`

## 🚨 Issue number

> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

> Summarize your work here.
> if you have any plots/diagrams/screenshots/tables, please attach them here.

This PR fixes a `FusedLinear1D_Col.from_native_module()` misimplementation that does not forward `n_fused` to the class constructor. As a result, if different `n_fused` other than 3 is given, it doesn't work as intended.

## 💥 Checklist before requesting a review

- [ ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [ ] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

### CODE REVIEW

**Comment by LRY89757** [comment]
Wow, Insu, nice to meet you here! 😀

**Comment by insujang** [comment]
Hi @LRY89757 ! Didn't know you were also a contributor here :D

**Comment by LRY89757** [comment]
Hi Insu, could you please update your pull request to the latest version of the main branch? Currently, your branch is unable to pass the CI tests, which is not your fault. I've added a hotfix today. Ensuring your branch is up-to-date will help resolve this issue. Thank you! @insujang :).

**Review by yuanheng-zhao — APPROVED** [review]
LGTM. Thank you for your contribution! @insujang

**Comment by LRY89757** [comment]
> Please anyone can merge the PR? I don't think I have permission to merge.

Sorry Insu, I didn't know you could not merge this pr. I thought you had forgotten it 😂.

**Pull request merged**
