### PR TITLE
[Fix] Fix Inference Example, Tests, and Requirements

### PR DESCRIPTION
**Pull request by yuanheng-zhao**
## 📌 Checklist before creating the PR

- [ ] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs
- [x] I have installed pre-commit: `pip install pre-commit && pre-commit install`

## 🚨 Issue number

> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

> Summarize your work here.
> if you have any plots/diagrams/screenshots/tables, please attach them here.

Clean and fix inference CI tests; fix inference examples; clean inference requirements. 

## 💥 Checklist before requesting a review

- [ ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [x] I have performed a self-review of my code
- [x] I have added thorough tests.
- [x] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

### CODE REVIEW

**Comment by yuanheng-zhao** [comment]
image

## Reason for example test timeout
For example test - language.openmoe, the CI will install colossalai from source (latest version) first, and then execute example tests. Part of the requirements of openmoe example test are 
```txt
colossalai >= 0.3.3
torch >= 1.8.1
transformers >= 4.20.0, <= 4.34.0
``` 
which will cause pip looking for different version of colossalai (e.g. `v0.3.6`, not the latest version anyway, since the latest version `v0.3.7` requires `transformers==4.36.2`) and re-installing it. And this causes timeout.

**Review by Courtesy-Xs — APPROVED** [review]
LGTM

**Review by yuehuayingxueluo — APPROVED** [review]
LGTM

**Comment by yuanheng-zhao** [comment]
This PR has been tested and passed all the "Build on PR" tests before the last commit of modifying an import path in openmoe example. But it cannot passed Example tests and build-on-pr tests at the same time, because we refactor extension module and the import path has changed in the current branch, as well as the branch `feature/colossal-infer`, however,  different versions of colossalai (`<=v0.3.6` vs `v0.3.7` or later - install from source) will be installed for example CI tests and for unit tests (build-on-pr tests) and thus either openmoe example test or `test_moe/` test, which imports modules from the openmoe example directory, will fail.

The import issue in OpenMOE example has been temporarily fixed in #5697

**Pull request merged**
