### PR TITLE
add colossalai kernel module

### PR DESCRIPTION
**Pull request by Shenggan**
add kernel module which including two parts:
1. jit: bias_dropout_add, bias_gelu
2. cuda_native: scale_mask_softmax, layernorm

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
Hi, @Shenggan. I think @ver217  has got a fused adam in the csrc folder, do we need it again in the kernel module?

**Comment by Shenggan** [comment]
I think kernel module only have bias_dropout_add, bias_gelu, scale_mask_softmax, layernorm and multihead_attention. I think the fused adam can unify into kernel module in the future.

**Comment by FrankLeeeee** [comment]
> I think kernel module only have bias_dropout_add, bias_gelu, scale_mask_softmax, layernorm and multihead_attention. I think the fused adam can unify into kernel module in the future.

I found colossalai/kernel/cuda_native/csrc/kernels/fused_adam_kernel.cu in the kernel module as well. Is it not used?

**Comment by Shenggan** [comment]
Is it not used now, and I remove `colossalai/kernel/cuda_native/csrc/kernels/fused_adam_kernel.cu` temporary.

**Review by FrankLeeeee — APPROVED** [review]

**Pull request merged**
