### PR TITLE
[coati]: bugfix. set default model_max_length;fix save_model method

### LINKED ISSUE #3364: [BUG]: Can not train boom-7b due to “int too big to convert” on V100(32GB)
### 🐛 Describe the bug

train_sft.sh file content:
```bash
torchrun --standalone --nproc_per_node=1 train_sft.py \
    --pretrain "/root/autodl-tmp/conda/colossal-chat/bloom-7b1/" \
    --model 'bloom' \
    --strategy colossalai_zero2 \
    --log_interval 10 \
    --save_path  /root/autodl-tmp/ai/colossal-ai-chat/colossal-chat-bloom-7b \
    --dataset /root/autodl-tmp/ai/colossal-ai-chat/dataset/instinwild_full.json \
    --batch_size 1 \
    --accimulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1 \
```
run `./train_sft.sh`, The error information is as follows:

```bash
OP colossalai._C.fused_optim already exists, skip building.
Time to load fused_optim op: 4.0531158447265625e-05 seconds
[03/31/23 11:21:01] INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:124 __init__
                    INFO     colossalai - colossalai - INFO: Loading data...
[03/31/23 11:21:02] INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:126 __init__
                    INFO     colossalai - colossalai - INFO: Loaded 103695 examples.
                    INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:129 __init__
                    INFO     colossalai - colossalai - INFO: Limiting dataset to 512 examples.
                    INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:132 __init__
                    INFO     colossalai - colossalai - INFO: Formatting inputs...
                    INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:140 __init__
                    INFO     colossalai - colossalai - INFO: Tokenizing inputs... This may take some time...
Traceback (most recent call last):
  File "train_sft.py", line 184, in <module>
    train(args)
  File "train_sft.py", line 106, in train
    train_dataset = SupervisedDataset(tokenizer=tokenizer,
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 141, in __init__
    data_dict = preprocess(sources, targets, tokenizer)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 111, in preprocess
    examples_tokenized, sources_tokenized = [_tokenize_fn(strings, tokenizer) for strings in (examples, sources)]
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 111, in <listcomp>
    examples_tokenized, sources_tokenized = [_tokenize_fn(strings, tokenizer) for strings in (examples, sources)]
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 83, in _tokenize_fn
    tokenized_list = [
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 84, in <listcomp>
    tokenizer(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2531, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2637, in _call_one
    return self.encode_plus(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2710, in encode_plus
    return self._encode_plus(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/models/bloom/tokenization_bloom_fast.py", line 158, in _encode_plus
    return super()._encode_plus(*args, **kwargs)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 500, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/models/bloom/tokenization_bloom_fast.py", line 147, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 420, in _batch_encode_plus
    self.set_truncation_and_padding(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 375, in set_truncation_and_padding
    self._tokenizer.enable_truncation(**target)
OverflowError: int too big to convert
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12067) of binary: /root/autodl-tmp/conda/colossal-chat/bin/python
Traceback (most recent call last):
  File "/root/autodl-tmp/conda/colossal-chat/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train_sft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-31_11:21:07
  host      : autodl-container-fbdc119552-21eb2858
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 12067)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

### Environment

torch==1.12.1+cu113
torchvision==0.13.1+cu113
torchaudio==0.12.1
Python==3.8.16
os=Ubuntu 20.04.4 LTS

### LINKED ISSUE #3366: [BUG]:
### 🐛 Describe the bug

image
Description:
When attempting to save a model using the save_model() method in the coati/trainer/rm.py module, an error is encountered with an unexpected keyword argument 'tokenizer'. The error traceback suggests that the error occurs in line 135 of the coati/trainer/rm.py file.

Steps to Reproduce:

Run the train_rm.sh script.
Call the save_model() method with the 'tokenizer' keyword argument.
Expected Behavior:
The save_model() method should save the model without any errors or issues.

Actual Behavior:
The save_model() method raises a TypeError with the message "save_model() got an unexpected keyword argument 'tokenizer'".

Possible Solution:
It seems that the save_model() method in the coati/trainer/rm.py module does not expect a 'tokenizer' keyword argument. To resolve the issue, either remove the 'tokenizer' argument when calling the save_model() method, or modify the method to accept the 'tokenizer' argument if it is required for the intended functionality.

Additional Information:

Version of Coati used: 1.0.0
Python version: 3.7
Operating system: Linux

### Environment

_No response_

### PR DESCRIPTION
**Pull request by cauyxy**
## 📌 Checklist before creating the PR

- [x] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [x] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number

fixed #3364 , close #3366

## 📝 What does this PR do?

To fix 3364
[set default model_max_length for bloom](https://github.com/hpcaitech/ColossalAI/commit/2cc61d5a910ac19331028bab85f74f7a39a75bca)
bloom origin tokenizer have no model_max_length,  if you don't set it , it use a big number cause tokenizer error

To fix 3366
[add 'tokenizer' parameter to the save_model() method in the Naive and DDP](https://github.com/hpcaitech/ColossalAI/commit/a53a13047d3d7c7a7a39e5457d00484b6a05043b)
The save_model() method in the Naive and DDP strategies inherits from their parent class, which does not include a tokenizer parameter. As a result, a call to the save_model() method with a tokenizer argument fails.

## 💥 Checklist before requesting a review

- [x] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [x] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [x] I have performed a self-review of my code
- [x] I have tested by myself.
- [x] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.
- [x] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

### CODE REVIEW

**Comment by cauyxy** [comment]
fix problem #3364

**Comment by cauyxy** [comment]
fix problem #3366

**Comment by x22x22** [comment]
ddp.py and naive.py nedd add import
```python
from typing import Optional
from transformers.tokenization_utils_base import PreTrainedTokenizerBase
```

**Comment by cauyxy** [comment]
> ddp.py and naive.py nedd add import
> 
> ```python
> from typing import Optional
> from transformers.tokenization_utils_base import PreTrainedTokenizerBase
> ```

i have fixed it. Thk u😊

**Comment by lierik** [comment]
Hello, thank you for you effort to fix this bug.
I meet the error too, but i review your code but find that, although you add the tokenizer into the parameters, but you don't add the "save" code in to save_model function.

Maybe you need to add the following codes in ddp and naive strategy as well?

from colossalai.logging import get_dist_logger
logger = get_dist_logger(__name__)

        if tokenizer is not None:
            logger.info(f'Saving tokenizer to {path}', ranks=[0])
            tokenizer.save_pretrained(path)
            logger.info(f'Tokenizer saved to {path} Successfully', ranks=[0])

**Comment by cauyxy** [comment]
> Hello, thank you for you effort to fix this bug. I meet the error too, but i review your code but find that, although you add the tokenizer into the parameters, but you don't add the "save" code in to save_model function.
> 
> Maybe you need to add the following codes in ddp and naive strategy as well?
> 
> from colossalai.logging import get_dist_logger logger = get_dist_logger(**name**)
> 
> # For ddp
> if tokenizer is not None: logger.info(f'Saving tokenizer to {path}', ranks=[0]) tokenizer.save_pretrained(path) logger.info(f'Tokenizer saved to {path} Successfully', ranks=[0])
> 
> # For naive
> if tokenizer is not None: logger.info(f'Saving tokenizer to {path}') tokenizer.save_pretrained(path) logger.info(f'Tokenizer saved to {path} Successfully')

I have already combined your proposal with this pr, thank you🥰

**Comment by cauyxy** [comment]
@Fazziekey

**Comment by ht-zhou** [comment]
Thank you for your nice work, can you fix the conflicts here?
image

**Pull request closed without merging**
