### PR TITLE
[hotfix] fix a weird bug.

### PR DESCRIPTION
**Pull request by super-dainiu**
## 📌 Checklist before creating the PR

- [x] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [x] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number

#3404, #3175, #2979
> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

> Summarize your work here.
> if you have any plots/diagrams/screenshots/tables, please attach them here.

## 💥 Checklist before requesting a review

- [x] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [x] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [x] I have performed a self-review of my code
- [x] I have added thorough tests.
- [x] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
@super-dainiu , can you explain more on your code change? Meanwhile, this PR has conflict with the main branch.

**Comment by super-dainiu** [comment]
this import will import colossalai.fx folder unexpectedly. this will further cause issues such as mismatches in ATen ops. I think we should remove this import since it is used for gemini. Gemini don't need fx.profiler.

**Comment by FrankLeeeee** [comment]
Ok, can you rebase your code with the main branch to resolve the conflict?

**Comment by super-dainiu** [comment]
okie, but I guess you might have a try too.

This problem happens when some versions of PyTorch call colossalai check -i or try to use some functionalities of Gemini.

**Comment by super-dainiu** [comment]
oh no why it's closed😂

**Comment by binmakeswell** [comment]
> oh no why it's closed😂

Ha, It seems that you closed it yourself. Welcome to resubmit a PR. Thanks.

**Comment by SAXSUN** [comment]
May I ask if this problem has been solved，Thanks

**Pull request closed without merging**
