### PR TITLE
[zero] polish sharded param name

### PR DESCRIPTION
**Pull request by feifeibear**
rename .data -> sharded_data_tensor in ShardedParamV2.
If we use param.data, it is misleading. People tend to believe it's a torch.Tensor. But actually its a ShardedTensor...

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
LGTM.

**Comment by ver217** [comment]
`col_attr.data` is used in many other files. Could you replace them?

**Comment by FrankLeeeee** [comment]
The CI failed in `tests/test_utils/test_bucket_tensor_copy.py`.
Screenshot 2022-03-22 at 11 13 34 AM

**Comment by ver217** [comment]
CI failed in `tests/test_utils/test_bucket_tensor_copy.py::test_bucket_copy`.
image

**Comment by ver217** [comment]
CI failed in `tests/test_utils/test_bucket_tensor_copy.py`.
image

**Review by ver217 — APPROVED** [review]

**Pull request merged**
