### PR TITLE
[example] add LoRA support

### PR DESCRIPTION
**Pull request by haofanwang**
This PR is motivated by [train_text_to_image_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py). ColossalAI framework can further optimize the training.

### CODE REVIEW

**Review by Fazziekey — APPROVED** [review]

**Review by Fazziekey — COMMENTED** [review]
Thanks a lot for your PR

**Comment by Fazziekey** [comment]
@haofanwang can you run `pip install pre-commit
&& pre-commit install` to fix your code style and pass our ci?  Here is the contributed guide: https://github.com/hpcaitech/ColossalAI/blob/main/CONTRIBUTING.md

**Comment by haofanwang** [comment]
@Fazziekey Done.

**Comment by Fazziekey** [comment]
@haofanwang  Thanks a lot for your Pull request, it is really amazing

**Pull request merged**
