### PR TITLE
MPI examples of ColossalAI - Retinal Vessel Segmentation and ViLT

### PR DESCRIPTION
**Pull request by ExtremeViscent**
A parallel example using ColossalAI, launching with MPI on multiple GPUs. Training model to automatically segment fundus image for blood vessels.

### CODE REVIEW

**Comment by ExtremeViscent** [comment]
This example is based on latest API

**Comment by FrankLeeeee** [comment]
Hi, @ExtremeViscent , your code has conflict with the main branch. Could you resolve the conflict first? :)

**Comment by ExtremeViscent** [comment]
> Hi, @ExtremeViscent , your code has conflict with the main branch. Could you resolve the conflict first? :)

Hi, conflict resolved. Thank you

**Comment by ExtremeViscent** [comment]
# ViLT (ITM and MLM example) - Data Parallel Example Added

**Comment by binmakeswell** [comment]
Hi, @ExtremeViscent . Thanks for your contribution. There are several pieces of advice.
1. Rebase your PR to 1 commit.
2. Add detail README for Retinal Vessel Segmentation.
3. Add expected running results or experiment log for ViLT.
4. Rename folders to be compatible with other examples.
5. Hide specific personal information, eg. path information of name in ViLT README.

**Comment by binmakeswell** [comment]
Hi, @ExtremeViscent , please submit example PR to https://github.com/hpcaitech/ColossalAI-Examples , sorry for the inconvenience. And again, please rebase your PR to 1 commit.

**Comment by FrankLeeeee** [comment]
Hi @ExtremeViscent  , thanks for your contribution. We are shifting the examples to an independent repo [ColossalAI-Examples](https://github.com/hpcaitech/ColossalAI-Examples). Welcome to put up your PR there. We have also updated the [tutorials and documentations](https://colossalai.org/). I will close this PR for now.

**Pull request closed without merging**
