### PR TITLE
Add Mistral support for Shardformer

### PR DESCRIPTION
**Pull request by eric8607242**
## 📌 Checklist before creating the PR

- [x] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [x] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number
#4835 #4836 

> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

Hi, I added a new policy and model to support Mistral with ShardFormer.
The current policy supports tensor parallel, fused normalization, and flash attention.

Although the minimum version requirement for Mitral is transformers==4.34.0.dev0 currently, it is still very excited to make ColossalAI support such impressive models!!!

## 💥 Checklist before requesting a review

- [x] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [x] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented
- [ ] 
## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

### CODE REVIEW

**Comment by eric8607242** [comment]
@flybird11111 
Hi, I create a new PR to `feature/shardformer` as you mentioned in #4836 
I appreciate your review for this PR.

Thanks

**Comment by flybird11111** [comment]
> @flybird11111 Hi, I create a new PR to `feature/shardformer` as you mentioned in #4836 I appreciate your review for this PR.
> 
> Thanks

Thank you for your contribution.

**Review by flybird11111 — APPROVED** [review]

**Comment by kno10** [comment]
was this reverted? why?

**Comment by CWHer** [comment]
> was this reverted in #5107? why?

No, this is not reverted.

**Pull request merged**
