### PR TITLE
An example for training deeplabv3+ on CamViD

### PR DESCRIPTION
**Pull request by JaclynZhong1127**
An example for training the deeplabv3+ on CamVid for segmentation

### CODE REVIEW

**Comment by JaclynZhong1127** [comment]
Adding an example for training deeplabv3+ on CamVid data set for segmentation,  which starts the training process using Colossal-AI.

**Comment by JaclynZhong1127** [comment]
Added an example for training deeplabv3+ on CamVid data set for segmentation, which starts the training process using Colossal-AI. @feifeibear @kurisusnowdeng @Shenggan Sorry for disturbing you, thanks a lot for spending time reviewing and helping!

**Review by feifeibear — COMMENTED** [review]
Hello, it is not appropriate to upload so many png files in the repo. Each of them is X KB.
You can commit the data using git lfs? or give a link to download?
_CamVid_data_parallel/cityscapes/cityscapesscripts/viewer/icons/zoom.png

**Comment by JaclynZhong1127** [comment]
> Hello, it is not appropriate to upload so many png files in the repo. Each of them is X KB. You can commit the data using git lfs? or give a link to download? _CamVid_data_parallel/cityscapes/cityscapesscripts/viewer/icons/zoom.png

Hello, the data link is https://www.cityscapes-dataset.com/downloads/, provided in the revised version.
The revised deeplabv3+_CamVid_data_parallel repo is also updated. Please check at your convenience. Thank you very much for your advice!

**Comment by JaclynZhong1127** [comment]
&nbsp;Thanks a lot for the suggestion. The revised version is added. Please take time reviewing when you are free. Thanks again！

Jiaping
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hpcaitech/ColossalAI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hpcaitech/ColossalAI] An example for training deeplabv3+ on CamViD (PR #135)





 
@feifeibear commented on this pull request.
 
Hello, it is not appropriate to upload so many png files in the repo. Each of them is X KB.
 You can commit the data using git lfs? or give a link to download?
 _CamVid_data_parallel/cityscapes/cityscapesscripts/viewer/icons/zoom.png
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by feifeibear** [comment]
> > Hello, it is not appropriate to upload so many png files in the repo. Each of them is X KB. You can commit the data using git lfs? or give a link to download? _CamVid_data_parallel/cityscapes/cityscapesscripts/viewer/icons/zoom.png
> 
> Hello, the data link is https://www.cityscapes-dataset.com/downloads/, provided in the revised version. The revised deeplabv3+_CamVid_data_parallel repo is also updated. Please check at your convenience. Thank you very much for your advice!

The png files still exist in the commit history of the repo, which increases the size of .git directory.
You can copy the modified files to a new branch and recommit?
Removing large files in commit history is tricky.
https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-the-git-repository

**Comment by kurisusnowdeng** [comment]
Hi, @JaclynZhong1127 . Thank you for the contribution! We would appreciate it if you can address the following points.

- Improve the consistency, e.g. in the readme instructions it says "run `python ./train_mytest.py`" but there is only a script called `train.py`.
- Please do not upload tensorboard log files.
- Instructions to prepare the dataset is still confusing ("Data" section in the readme). I guess just one line of bash command as `git clone https://github.com/alexgkendall/SegNet-Tutorial ./data` is enough.
- Also, we suggest to use the environment variable `DATA` to provide the dataset path instead of a fixed path in the python scripts, and you can use the path `./data` when `DATA` is not set.
- What are `cityscapes.py` and `utils.py` used for? We have not found where the classes or functions are actually used.

**Comment by kurisusnowdeng** [comment]
Also a suggestion to clean the commit history is to rebase your commits and squash them into a single commit.

**Comment by JaclynZhong1127** [comment]
Thank you for all your valuable suggestions and efforts @feifeibear @kurisusnowdeng. I am glad to do so. The issues are addressed point by point. Please check them at your convenience. Thanks again!

**Comment by FrankLeeeee** [comment]
Hi, @JaclynZhong1127 . Have you deleted your main branch?

**Comment by FrankLeeeee** [comment]
Hi, can you remove the images and tensorboard logs from your commit? These will make the git file bulky. Meanwhile, we have shifted the examples in the new [repository](https://github.com/hpcaitech/ColossalAI-Examples). Would you mind put up a PR there? I will close this PR for now. Feel free to raise any issue in the new examples repository if you encounter any problem.

**Pull request closed without merging**
