### PR TITLE
[refactor] restructure configuration files

### LINKED ISSUE #2976: [PROPOSAL]: Refactor configuration files
### Proposal

It'd be nice if we could minimize the number of configuration files for the project. Instead of a separate `.style.yapf`, `pytest.ini`, `.clang-format` and `.isort.cfg`, we could have all the configurations within a `pyproject.toml` file leading to a overall minimal code structure.

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
## 📌 Checklist before creating the PR

- [x] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [x] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number

Fixes #2976

## 📝 What does this PR do?

This PR aims to make the project structure more minimal by moving configuration of all linters and code quality tools into either the `pyproject.toml` or the `.pre-commit-config.yaml` file.

It also moves the `CONTRIBUTING.md` file inside the `.github/` dir. Github looks for a contribution guideline file in the following order: `.github dir > project root > docs dir` ([source](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)). Moving the file to the `.github/` dir leads to a minimal project structure without any functional change.

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.

### CODE REVIEW

**Comment by binmakeswell** [comment]
Hi @SauravMaheshkar Thank you very much for your contribution!

**Comment by SauravMaheshkar** [comment]
> Hi @SauravMaheshkar Thank you very much for your contribution!

Looking forward to contributing more 😄

**Comment by SauravMaheshkar** [comment]
Looks like the tests passed 😄

**Review by FrankLeeeee — APPROVED** [review]

**Comment by FrankLeeeee** [comment]
> Looks like the tests passed 😄

Awesome! Thank you very much!

**Pull request merged**
