### PR TITLE
An example for hyperspectral image processing.

### PR DESCRIPTION
**Pull request by hnqin-xdu**
An example of the application of ColossalAI in hyperspectral image processing in the Google Colab platform.

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
Hi @hnqin-xdu, thank you very much for your contribution. The current version is still an unstable beta version and we are updating the API for better usability. Could you integrate your example with the latest API? I will notify you when the new API is merged into main branch. :)

**Comment by FrankLeeeee** [comment]
Meanwhile, it will be good to rebase the commits into one commit so that the git log will look cleaner

**Comment by hnqin-xdu** [comment]
> Hi @hnqin-xdu, thank you very much for your contribution. The current version is still an unstable beta version and we are updating the API for better usability. Could you integrate your example with the latest API? I will notify you when the new API is merged into main branch. :)

My pleasure. All right. I will integrate my example with the latest API after you notify me.

**Comment by hnqin-xdu** [comment]
> Meanwhile, it will be good to rebase the commits into one commit so that the git log will look cleaner

All right. I will rebase the commits into one commit. And I will improve this example by adding the necessary introduction and annotation later.

**Comment by FrankLeeeee** [comment]
Hi, @hnqin-xdu. The new api and documentation are updated, you can refer to the examples folder for some demo. Feel free to contact me if you encounter any issue. 😃

**Comment by FrankLeeeee** [comment]
Hi @hnqin-xdu , thanks for your contribution. We are shifting the examples to an independent repo [ColossalAI-Examples](https://github.com/hpcaitech/ColossalAI-Examples). Welcome to put up your PR there. I will close this PR for now.

**Pull request closed without merging**
