### PR TITLE
Added ViLT data parallel example

### PR DESCRIPTION
**Pull request by ExtremeViscent**
Colossal-AI data parallel implementation for the Vision-and-Language Transformer.
Training on COCO captioning dataset for image text matching (ITM) and masked language (MLM) models.

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
Cool @ExtremeViscent , we will review this PR and let you know soon :)

**Comment by FrankLeeeee** [comment]
Hi, can you remove the images and output logs from your commit? These will make the git file bulky. Meanwhile, we have shifted the examples in the new [repository](https://github.com/hpcaitech/ColossalAI-Examples). Would you mind put up a PR there? I will close this PR for now. Feel free to raise any issue in the new examples repository if you encounter any problem.

**Comment by FrankLeeeee** [comment]
Hi @ExtremeViscent , we notice that you changed your `setup.py`. May we know if you encounter any problem when installing ColossalAI? We'd love to hear from you and help you fix this problem.

@ver217 , can you take charge of this issue?

Screenshot 2022-01-20 at 2 19 10 PM

**Comment by ExtremeViscent** [comment]
> Hi @ExtremeViscent , we notice that you changed your `setup.py`. May we know if you encounter any problem when installing ColossalAI? We'd love to hear from you and help you fix this problem.
> 
> @ver217 , can you take charge of this issue?
> 
> Screenshot 2022-01-20 at 2 19 10 PM

Hi,
This is a specific issue in my local environment. My CUDA toolkit is 11.4 while PyTorch is built on 11.3, causing a minor mismatch. Following the advice of Apex, commenting out version check does not usually cause error. Therefore, I bypassed it.

**Comment by FrankLeeeee** [comment]
Hi, thanks for your information. We will consider making this check optional for installation.

**Pull request closed without merging**
