### PR TITLE
[coati] Fix LlamaCritic

### LINKED ISSUE #3428: maybe LlamaModel？
https://github.com/hpcaitech/ColossalAI/blob/b09adff724c2bbded1c71cc51a707f736a0e2899/applications/Chat/coati/models/llama/llama_critic.py#L31

### PR DESCRIPTION
**Pull request by gongel**
## 🚨 Issue number

fixed #3428

## 📝 What does this PR do?

mv LlamaForCausalLM to LlamaModel

### CODE REVIEW

**Comment by JThh** [comment]
LGTM.

**Comment by TongLi3701** [comment]
Thanks for your contribution, @gongel ! 

Could you also remove unused imports such as `AutoModelForCausalLM` ? 

Then I will approve, thanks!

**Comment by gongel** [comment]
> Thanks for your contribution, @gongel !
> 
> Could you also remove unused imports such as `AutoModelForCausalLM` ?
> 
> Then I will approve, thanks!

DONE

**Review by TongLi3701 — APPROVED** [review]
Thanks! 

Approved.

**Pull request merged**
