### PR TITLE
Feature/cli

### PR DESCRIPTION
**Pull request by YuliangLiu0306**
add CLI launch feature.

### CODE REVIEW

**Comment by feifeibear** [comment]
Please close Run Build and Test label if the feature is under developpment

**Comment by FrankLeeeee** [comment]
Hi @YuliangLiu0306 , can you split this PR into two PRs. One is for multi-node launching and the other is for micro-benchmarking.

**Comment by YuliangLiu0306** [comment]
This PR will be split into two PRs.

**Comment by FrankLeeeee** [comment]
> This PR will be split into two PRs.

Great!

**Pull request closed without merging**
