### PR TITLE
Initialize xpu support

### PR DESCRIPTION
**Pull request by abhilash1910**
## 📌 Checklist before creating the PR
.
- Initializing  PR to support xpu devices [Draft]

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
Hey @abhilash1910 , happy to see your contribution.

**Comment by abhilash1910** [comment]
Thanks @FrankLeeeee  , I will work on this PR to enable for Intel devices.

**Comment by FrankLeeeee** [comment]
Sure, do let us know if you require any help, more than willing to help :)

**Comment by abhilash1910** [comment]
I added one in #4004  , let me know if its ok to continue there , and can close this one?

**Comment by FrankLeeeee** [comment]
Hi @abhilash1910 , thanks for your new pull request. I would recommend you check out from the develop branch to start your development. The general procedure will look like this:


1. fork this repository as you have already done

2. check out from develop

```bash
cd ColossalAI

# set upstream to our repository
git remote add upstream https://github.com/hpcaitech/ColossalAI.git

# sync with our development branch
git fetch upstream
git checkout develop
git rebase upstream/develop

# check out a new branch from the develop branch
git checkout -b feature/xpu-support
```

**Comment by abhilash1910** [comment]
@FrankLeeeee #4006  closing this and #4004

**Pull request closed without merging**
