### PR TITLE
[zero] fix bert unit test

### PR DESCRIPTION
**Pull request by ver217**
1. Fix bert unit test: disable dropout
2. Enable test sharded model v2

### CODE REVIEW

**Review by FrankLeeeee — APPROVED** [review]

**Comment by FrankLeeeee** [comment]
I think this error occurs for BERT
Screenshot 2022-03-09 at 2 10 43 PM

**Comment by ver217** [comment]
> I think this error occurs for BERT Screenshot 2022-03-09 at 2 10 43 PM

Do you have any idea?

**Comment by ver217** [comment]
> I think this error occurs for BERT Screenshot 2022-03-09 at 2 10 43 PM

This error occurs when using naive AMP.

**Comment by FrankLeeeee** [comment]
Yes, I have no idea why it occurs. I think can limit the test cases to resnet, nested model and repeatedly computed layers for that test.

**Comment by ver217** [comment]
> Yes, I have no idea why it occurs. I think can limit the test cases to resnet, nested model and repeatedly computed layers for that test.

Right, I ignore BERT and the test pass. I will skip bert now.

**Pull request merged**
