### PR TITLE
[formatting] fixed code format with pre-commit hook

### PR DESCRIPTION
**Pull request by binmakeswell**

### CODE REVIEW

**Review by FrankLeeeee — APPROVED** [review]

**Review by FrankLeeeee — CHANGES_REQUESTED** [review]
do not include dropout kernel

**Comment by FrankLeeeee** [comment]
Screenshot 2022-07-13 at 11 34 32 AM

Do not change these files as they can lead to build failure. This occurred last time.

**Comment by binmakeswell** [comment]
Do you mean all files in the ‘kernal’ directory should not be modified in this way？

**Comment by FrankLeeeee** [comment]
> Do you mean all files in the ‘kernal’ directory should not be modified in this way？

Yes.

**Review by FrankLeeeee — APPROVED** [review]

**Pull request merged**
