### PR TITLE
[shardformer] Support customized policy for llamav2 based model with HybridParallelPlugin

### PR DESCRIPTION
**Pull request by eric8607242**
## 📌 Checklist before creating the PR

- [x] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number
#4613 
#4614 
#4612 
## 📝 What does this PR do?

Hi, 
I sent a PR #4614  on 09/05 to add an argument `policy` for `HybridParallelPlugin` to enable `ShardFormer` for customized models, and add a new attribute replacement for llama policy for llamav2 tensor parallelism support.
However, the PR #4614 is closed because the branch `feature/shardformer` is deleted by the PR #4612.
I cherry-pick my commit and resend a PR again. Thanks!

In this PR, I have two modifications for `ShardFormer`.
1. I created a new argument `policy` for `HybridParallelPlugin`, which enables user can apply `HybridParallel` to their own model with customized `Policy`.
2. I add a new attribute replacement `self_attn.num_key_value_heads` for `LlamaPolicy`. The attribute is new for LLaMAv2, without this attribute replacement, I can not apply tensor parallelism on LLaMAv2 successfully.

## 💥 Checklist before requesting a review

- [x] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [x] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

### CODE REVIEW

**Comment by flybird11111** [comment]
> Hi, @flybird11111 The PR #4614 is moved to here. Thanks

HI，Can you please revert the changes made in the 'hybrid_parallel_plugin.py'?

**Comment by eric8607242** [comment]
Hi, @flybird11111 

Does HybridParallelPlugin not plan to support customized policies?

**Comment by flybird11111** [comment]
> Hi, @flybird11111
> 
> Does HybridParallelPlugin not plan to support customized policies?
You can refer to this document for custom policy development.  https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/shardformer/README.md， Sorry, because I urgently needed to use your pull request, I went ahead and made the changes myself.

**Comment by eric8607242** [comment]
Hi,

Got it. Thanks for your review

**Comment by flybird11111** [comment]
> Hi,
> 
> Got it. Thanks for your review



> Hi,
> 
> Got it. Thanks for your review

Is there one more thing you can help with? Can you assist in upgrading transformers so that we can test with LLAM2?

**Review by flybird11111 — APPROVED** [review]

**Review by FrankLeeeee — APPROVED** [review]

**Pull request merged**
