### PR TITLE
Added two examples

### PR DESCRIPTION
**Pull request by rahulgupta9202**
Added two examples

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
Hi Gupta, thanks for your contribution. We are updating the system API for better usability. The PR is expected to to be approved today. Could you use the latest API for this commit later? Thanks!

**Comment by FrankLeeeee** [comment]
Meanwhile, it will be good to have more meaningful commit message :)

**Comment by rahulgupta9202** [comment]
> Hi Gupta, thanks for your contribution. We are updating the system API for better usability. The PR is expected to to be approved today. Could you use the latest API for this commit later? Thanks!

Yeah , I'll make the changes today. Thanks!

**Comment by rahulgupta9202** [comment]
> Meanwhile, it will be good to have more meaningful commit message :)

Yes, I will get on it. Thanks!

**Comment by Rudransh1084** [comment]
The latest commit is based on the updated API
With:
1- Example of application of ColossalAI on CIFAR-10 Dataset using Transfer Learning on Resnet50
2- Example of application of ColossalAI on an external Dataset(CatsVDog dataset) using Transfer Learning on Resnet 50 CNN

**Comment by rahulgupta9202** [comment]
The latest commit is based on the updated API
With:
1- Example of application of ColossalAI on CIFAR-10 Dataset using Transfer Learning on Resnet50
2- Example of application of ColossalAI on an external Dataset(CatsVDog dataset) using Transfer Learning on Resnet 50 CNN

**Comment by FrankLeeeee** [comment]
Hi, @rahulgupta9202 , thank you for your work! You can now visit the web documentation and example folder for more details. I notice that the example you provided is about resnet, which has already been in the example folder. Would you like to try another network/application? Meanwhile, it will be good to rebase your commits into one commit so that the git log looks cleaner. Feel free to @ me if you need any help! 😃

**Comment by rahulgupta9202** [comment]
@FrankLeeeee Sorry for the late response! I can try and work on another application and I will also rebase my commits. 
Thanks for your help!

**Comment by FrankLeeeee** [comment]
Hi @rahulgupta9202  , thanks for your contribution. We are shifting the examples to an independent repo [ColossalAI-Examples](https://github.com/hpcaitech/ColossalAI-Examples). Welcome to put up your PR there. We have also updated the [tutorials and documentations](https://colossalai.org/). I will close this PR for now.

**Pull request closed without merging**
