### PR TITLE
modefied the pp build for ckpt adaptation

### PR DESCRIPTION
**Pull request by Gy-Lu**
This pr is same as #795 .

### CODE REVIEW

**Review by feifeibear — APPROVED** [review]

**Review by ver217 — APPROVED** [review]

**Comment by Gy-Lu** [comment]
I will rerun the CI this night.

**Comment by feifeibear** [comment]
@Gy-Lu just run these failed case locally and post a snapshot here. We will merge you PR.
image

**Comment by Gy-Lu** [comment]
> @Gy-Lu just run these failed case locally and post a snapshot here. We will merge you PR. image

OK

**Comment by feifeibear** [comment]
@Gy-Lu did you check the unit tests of the failed cases?

**Comment by Gy-Lu** [comment]
> @Gy-Lu did you check the unit tests of the failed cases?

Yes. But I think I should do more tests to ensure it works well.
I will turn this pr into draft.

**Comment by Gy-Lu** [comment]
@feifeibear @ver217 
Hi, I have updated the PP builder for ckpt.
And fixed the bug when num_chunk=1 with interleaved PP.
Here is the unit test.
image

**Review by ver217 — APPROVED** [review]

**Review by feifeibear — APPROVED** [review]

**Pull request merged**
