### PR TITLE
[hotfix] Fix typos for supporting distributed training

### PR DESCRIPTION
**Pull request by haofanwang**
This PR fixes the distributed training problem mentioned in https://github.com/hpcaitech/ColossalAI/issues/2407.

### CODE REVIEW

**Review by feifeibear — COMMENTED** [review]
@haofanwang thanks for your warm-hearting contribution. However, I believe the original version should not be modified. The original intention is that if the backend is gloo, we don't need to use group_cpu but just use group directly.

**Comment by haofanwang** [comment]
I see, but is it normal? As gloo backend is usually for distributed CPU training. @feifeibear 

The default backend is [nccl](https://github.com/hpcaitech/ColossalAI/blob/93f62dd15288379355d5f4f41c3959e681f5ac41/colossalai/initialize.py#L65), which makes claim "dist.get_backend() != 'gloo'" True, and group_cpu is always used in such a case. To be more specific, [gpc.init_global_dist](https://github.com/hpcaitech/ColossalAI/blob/93f62dd15288379355d5f4f41c3959e681f5ac41/colossalai/initialize.py#L100) and [gpc.init_parallel_groups()](https://github.com/hpcaitech/ColossalAI/blob/93f62dd15288379355d5f4f41c3959e681f5ac41/colossalai/initialize.py#L103) lead to [connection issue](https://github.com/hpcaitech/ColossalAI/issues/2407). However, with above changes, distributed GPU training works fine.

**Comment by FrankLeeeee** [comment]
@feifeibear do we still need this CPU process group? Many users encounter environment issues when init this group.

**Comment by kurisusnowdeng** [comment]
Hi @haofanwang . In our design, `get_group()` returns the default group (which can be nccl, gloo, etc). Meanwhile, as the default group usually is used by gpu communication, we need `get_cpu_group()` to return a gloo group for cpu communication. In your case, just specify the default backend and group as gloo, and then `get_cpu_group()` will redirect you to the default group. However, you are duplicating the gloo group. The change is sadly not how it is supposed to work.

**Comment by feifeibear** [comment]
@kurisusnowdeng @haofanwang Can we close this PR? It looks like the problem has been solved.

**Pull request closed without merging**
