### PR TITLE
[amp] add torch amp test

### PR DESCRIPTION
**Pull request by xcnick**
This pr add a torch amp unit test, compare torch amp and apex amp.

### CODE REVIEW

**Review by feifeibear — APPROVED** [review]
Perfect! Thanks Chi!

**Comment by feifeibear** [comment]
@xcnick can you fix the CI error
https://github.com/hpcaitech/ColossalAI/actions/runs/3429779426/jobs/5715859214

**Comment by xcnick** [comment]
@feifeibear This may be caused by an error in the upstream library apex, [this pr](https://github.com/NVIDIA/apex/pull/1282) is ready to fix this error, but it has not been merged so far.

I manually modified the Apex source code according to the pr in my local environment, and the unit test passed.

**Comment by feifeibear** [comment]
> @feifeibear This may be caused by an error in the upstream library apex, [this pr](https://github.com/NVIDIA/apex/pull/1282) is ready to fix this error, but it has not been merged so far.
> 
> I manually modified the Apex source code according to the pr in my local environment, and the unit test passed.

That won't work for CAI. Since we must depend on a stable apex version. Can you think of some way to bypass this problem?

**Comment by xcnick** [comment]
ok，I'll figure it out.

**Pull request merged**
